### ISSUE TITLE
Hourly Forecasts

### ISSUE THREAD

**Issue by marcnjaramillo** [MLH-Fellowship/prep-project-22.NOV.PREP.2#1]
Allow the user to put a time + date in to get an idea of what the weather will be like then. At the moment, it only displays the weather right now.

**Comment by 0904-mansi** [comment]
I would like to work on this issue.

**Comment by 0904-mansi** [comment]
I would like to work on this issue.

**Comment by ciradu2204** [comment]
I can work on this

**Comment by IvyJeptoo** [comment]
Group 3 working on this
