### ISSUE TITLE
Main weather card

### ISSUE THREAD

**Issue by kph4m** [MLH-Fellowship/prep-project-22.NOV.PREP.2#15]
The main weather card that users will view. Information includes
- City
- Time
- Temp
- Icon for temp
- Description
- Feels like
- Humidity
- Wind Speed
- Temp min
- Temp max

![image](https://user-images.githubusercontent.com/76819117/202044393-dd837b1c-05cb-4577-82e0-afb313402dfc.png)

**Comment by youngjun827** [comment]
I can do this!

**Comment by miador** [comment]
The person who will be working on this issue, please open the PR into #7
Reach out to @ShivamTyagi12345 for more info

**Comment by ciradu2204** [comment]
I can work on this

**Comment by indevi** [comment]
> I can work on this

Hey @ciradu2204 You have two options to solve this issue:

**OPTION Number 1:** 
---

You can Copy @youngjun827 's code so far and start making your changes in that code to fix that issue.
Pros: Its easy to do
Cons: It takes away @youngjun827  code contribution credits in your name

**OPTION Number 2:** 
---
Step 1: You can ask @youngjun827  to create a New PR from a new Branch (_which will be a copy of his current **main** branch_) with the existent code he has. 
Step 2: Make your changes in that   Young's new Branch which fixes 
- https://github.com/MLH-Fellowship/prep-project-22.NOV.PREP.2/issues/15

Step 3: We merge Young's new branch

Pros: This counts each individual's fair contribution
Cons: Seems tough to accomplish at the first glance, (Its easyyy Ngl)

**Comment by ciradu2204** [comment]
okay, thanks. I will work on it
