### ISSUE TITLE
Saved locations

### ISSUE THREAD

**Issue by kph4m** [MLH-Fellowship/prep-project-22.NOV.PREP.2#16]
Save searched cities and display them by clicking a button on the navbar, which will show a popup with the saved cities.
![image](https://user-images.githubusercontent.com/76819117/202045350-e541d801-39af-4cb7-8f49-7d9176cd76c1.png)

The saved cities will be in a card format and contain the following info:
- City, Country
- Temp
- Icon based on temp
- Description
- Humidity
- Wind speed

The card will display updated data, not the data when it was saved.

The user will be able to click on the card and it will re-search the city and show the main page.
![image](https://user-images.githubusercontent.com/76819117/202045954-0513e677-f1f6-434d-a940-c3c22c0c2021.png)

The save button is located at the right edge near the search bar
![image](https://user-images.githubusercontent.com/76819117/202046410-933f0003-875c-4b11-9d35-30e8a3edd428.png)

**Comment by trinhcaokhoa** [comment]
I will work on this

**Comment by miador** [comment]
I believe this is resolved
