### ISSUE TITLE
Suggested activities

### ISSUE THREAD

**Issue by kph4m** [MLH-Fellowship/prep-project-22.NOV.PREP.2#17]
List activities the user could do based on the weather at the bottom of the page.

![image](https://user-images.githubusercontent.com/76819117/202048283-2f03b6e9-bf2d-4d63-86a7-43660c7279ce.png)

**Comment by jerrendang** [comment]
Team 1 is working on this.

**Comment by grace-omotoso** [comment]
@jerrendang what is the progress of this issue. It will be great if we have it in but no pressure
