### ISSUE TITLE
Add map

### ISSUE THREAD

**Issue by kph4m** [MLH-Fellowship/prep-project-22.NOV.PREP.2#33]
Map will show the location of the city besides the main weather card

![image](https://user-images.githubusercontent.com/76819117/202581896-bf720681-c61b-4d03-b6c3-383c0afdb59e.png)

**Comment by kph4m** [comment]
I can do this.

**Comment by armanmoztar** [comment]
you can use the geoapify api for this which might help, it's a bit similar to my autocomplete issue
