### ISSUE TITLE
Autocomplete for cities

### ISSUE THREAD

**Issue by marcnjaramillo** [MLH-Fellowship/prep-project-22.NOV.PREP.2#6]
At the moment, when you type in a city, it won't help you finish your entry with suggestions. A cool feature would be if it had a drop down menu that suggested locations similar to the name. For example, if I type in `Cambridge`, it could tell me `Cambridge, MA, USA` or `Cambridge, UK` to help users get the right answers!

**Comment by armanmoztar** [comment]
I can work on this

**Comment by miador** [comment]
Would be good if we could have this feature on monday

**Comment by grace-omotoso** [comment]
@armanmoztar is there any progress with this? Do you need any assistance?

**Comment by armanmoztar** [comment]
> @armanmoztar is there any progress with this? Do you need any assistance?

Yeah I've messaged Cynthia about it to see if she's able to help me on this and I can also share my progress at todays meeting

**Comment by armanmoztar** [comment]
Kheim is helping me with this one
