### ISSUE TITLE
Style webpage according to Figma file

### ISSUE THREAD

**Issue by kph4m** [MLH-Fellowship/prep-project-22.NOV.PREP.2#74]
Style the application based on the designs on Figma

**Comment by kph4m** [comment]
I can do this

**Comment by IvyJeptoo** [comment]
@kpham841 I think the cards need a darker shade because it blends in with the background videos and it's readability is kind of hard

**Comment by kph4m** [comment]
Is there a specific background that makes it hard to read?

**Comment by IvyJeptoo** [comment]
If you can see the cards are kind of hard to read. also the navbar contents are kind of overflowing or something. 
![Screenshot from 2022-11-24 12-36-12](https://user-images.githubusercontent.com/98116399/203749264-e5e785c2-f78a-4e92-82b2-d52056af10c9.png)

**Comment by kph4m** [comment]
This is the updated commit: https://deploy-preview-92--mlh-prep-22-nov-prep-2-project.netlify.app/

**Comment by IvyJeptoo** [comment]
Great! looks amazing
